name: Build and Push Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.DEVOPS_TOKEN }}
          fetch-tags: true

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GHCR
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEVOPS_TOKEN }}

      # Generate semantic version
      - name: Generate Semantic Version
        id: version
        run: |
          # Use git describe to generate a version based on tags
          version=$(git describe --tags --always --dirty="-dev")
          echo "version=${version}" >> $GITHUB_ENV

      # Build and Push Images
      - name: Build and Push Images
        run: |
          docker buildx bake --file docker-bake.hcl \
            --set base.tags=ghcr.io/${{ github.repository }}-base:${{ env.version }} \
            --set cudnn.tags=ghcr.io/${{ github.repository }}-cudnn:${{ env.version }} \
            --push
